version: '2'
services:
  web:
    build: .
    image: jpz13/roomly
    links:
      - mysql
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
    command: bash -c "npm rebuild node-sass & npm start"
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: mysql:5.7.17
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: roomly
